# Sources : https://docs.travis-ci.com/user/getting-started/

# ---------------- #
# --- Settings --- #
# ---------------- #

language: php

php:
    - 5.6

# ----------------------- #
# --- Build LifeCycle --- #
# ----------------------- #
script:
    - phpunit your_test_php_file.php
